# Generated by Django 4.2.11 on 2026-03-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pool_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
