# Generated by Django 4.2.29 on 2026-03-27 02:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_win', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bets',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='BetSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potential_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bets', models.ManyToManyField(related_name='slips', to='bets.bet')),
            ],
            options={
                'db_table': 'bet_slips',
            },
        ),
    ]
