# Generated by Django 4.2.29 on 2026-03-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
